name: mailit frontend

on:
    push:
        branches: 
            - master
    pull_request: 
        branches: 
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Node.js 
              uses: actions/setup-node@v3
              with:
                node-version: 22
                cache: npm

            - name: Install Dependencies
              run: npm install 
              
            - name: Build the Application
              run: npm run build
              
            - name: Deploy to vercel
              run:  npx vercel deploy --prod --yes --token ${{secrets.CICD_WORKFLOW_TOKEN}} --scope swapnilsonkers-projects --project mail-it 
